# https://jekyllrb.com/docs/configuration/

title: Terminal Theme
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
domain:
# the base hostname & protocol for your site, e.g. http://example.com
url:
# the subpath of your site, e.g. /blog
baseurl: /jekyll-terminal-theme

# timezozne e.g. Asia/Seoul
timezone: Asia/Seoul

# this is menu
menu:
  - text: Menu
  - text: About
    url: /about
  - text: Tags
    url: /tags
  - text: Categories
    url: /categories
  - text: Series
    url: /series
  - text: u can write html like
  - html: <table style="margin:0 auto"><thead><tr><th style="text-align:center">1</th><th style="text-align:center">2</th><th style="text-align:center">3</th></tr></thead><tbody><tr><td style="text-align:center">4</td><td style="text-align:center">5</td><td style="text-align:center">6</td></tr><tr><td style="text-align:center">7</td><td style="text-align:center">8</td><td style="text-align:center">9</td></tr></tbody></table>

footer:
  name: your-name-here
  link: https://github.com/fienestar/jekyll-terminal-theme

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

css: assets/css
js: assets/js
images: assets/images

external-posts-category-name: external-links # add external post using `redirect: {uri}` in post front matter
# catalog: true # add catalog to posts

# theme version
version: 1.0.1
