# https://jekyllrb.com/docs/configuration/

title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
domain:
# the base hostname & protocol for your site, e.g. http://example.com
url:
# the subpath of your site, e.g. /blog
baseurl:

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
